### ISSUE TITLE
Erratum in Start/Stop Sampling SDK communication protocol command

### ISSUE THREAD

**Issue by ryan-brazeal-ufl** [Livox-SDK/Livox-SDK#10]
Hello,

In section 4.1 of the General CMD Set section of your SDK documentation, you state that the Start/Stop Sampling command (0x04) uses the values of **0x00 to Start Sampling and 0x01 to Stop Sampling**. After working (and ultimately wasting) over half a day on trying to simply get my Mid-40 to begin transmitting point cloud data packets, it turns out that your documentation is incorrect and **these two commands are in fact reversed!!**

I sure hope this helps someone else out and saves them the time and headaches.

Ryan

**Comment by Livox-SDK** [comment]
Hi, Ryan:
I am sorry to say it again, you are right, these two commands are indeed reversed!
If you find any bug in our SDK documentation,please let us know and post them here!
thanks ,ryan!
