### ISSUE TITLE
Device State Error Code 0X00000000

### ISSUE THREAD

**Issue by Ganymedes-wang** [Livox-SDK/Livox-SDK#102]
执行` ./lidar_sample`，
显示“StateChange”和“Device State Error Code”，输出日志文件如下：

`Livox SDK initializing.
Livox SDK has been initialized.
Livox SDK version 2.3.0 .
Start discovering device.

[2020-12-16 15:37:25.866] [console] [info]  Broadcast broadcast code: 0TFDH9U006G7851  [device_discovery.cpp] [OnBroadcast] [150]
Receive Broadcast Code 0TFDH9U006G7851
[2020-12-16 15:37:25.866] [console] [info] LocalIP: 192.168.1.39  [device_discovery.cpp] [OnBroadcast] [201]
[2020-12-16 15:37:25.866] [console] [info] DeviceIP: 192.168.1.38  [device_discovery.cpp] [OnBroadcast] [202]
[2020-12-16 15:37:25.866] [console] [info] Command Port: 55501  [device_discovery.cpp] [OnBroadcast] [203]
[2020-12-16 15:37:25.866] [console] [info] Data Port: 56001  [device_discovery.cpp] [OnBroadcast] [204]
[2020-12-16 15:37:25.890] [console] [info] New Device  [device_discovery.cpp] [OnData] [99]
[2020-12-16 15:37:25.890] [console] [info] Handle: 0  [device_discovery.cpp] [OnData] [100]
[2020-12-16 15:37:25.890] [console] [info] Broadcast Code: 0TFDH9U006G7851  [device_discovery.cpp] [OnData] [101]
[2020-12-16 15:37:25.890] [console] [info] Type: 1  [device_discovery.cpp] [OnData] [102]
[2020-12-16 15:37:25.890] [console] [info] IP: 192.168.1.38  [device_discovery.cpp] [OnData] [103]
[2020-12-16 15:37:25.890] [console] [info] Command Port: 55501  [device_discovery.cpp] [OnData] [104]
[2020-12-16 15:37:25.890] [console] [info] Data Port: 56001  [device_discovery.cpp] [OnData] [105]
[2020-12-16 15:37:25.890] [console] [info]  Send Command: Set 0 Id 2 Seq 3  [command_channel.cpp] [Send] [243]
[2020-12-16 15:37:25.914] [console] [info]  Recieve Ack: Set 0 Id 2 Seq 3  [command_handler.cpp] [OnCommand] [118]
[WARNING] Lidar sn: [0TFDH9U006G7851] Connect!!!
Device Working State 5
Device State Error Code 0X00000000
Device feature 0
[2020-12-16 15:37:25.914] [console] [info]  Send Command: Set 0 Id 2 Seq 4  [command_channel.cpp] [Send] [243]
[2020-12-16 15:37:25.938] [console] [info]  Update State to 1, device connect true  [device_manager.cpp] [UpdateDeviceState] [257]
[WARNING] Lidar sn: [0TFDH9U006G7851] StateChange!!!
Device Working State 1
Device State Error Code 0X00000000
Device feature 0
[2020-12-16 15:37:25.938] [console] [info]  Recieve Ack: Set 0 Id 2 Seq 4  [command_handler.cpp] [OnCommand] [118]
firm ver: 3.8.0.0
[2020-12-16 15:37:25.938] [console] [info]  Send Command: Set 0 Id 4 Seq 6  [command_channel.cpp] [Send] [243]
[2020-12-16 15:37:25.962] [console] [info]  Recieve Ack: Set 0 Id 4 Seq 6  [command_handler.cpp] [OnCommand] [118]
OnSampleCallback statue 0 handle 0 response 0 
data_type 0 packet num 100
data_type 0 packet num 200
data_type 0 packet num 300
data_type 0 packet num 400
data_type 0 packet num 500
data_type 0 packet num 600
data_type 0 packet num 700
data_type 0 packet num 800
data_type 0 packet num 900
data_type 0 packet num 1000
data_type 0 packet num 1100
data_type 0 packet num 1200
data_type 0 packet num 1300
data_type 0 packet num 1400
data_type 0 packet num 1500
data_type 0 packet num 1600
data_type 0 packet num 1700
data_type 0 packet num 1800
data_type 0 packet num 1900
data_type 0 packet num 2000
data_type 0 packet num 2100
data_type 0 packet num 2200
data_type 0 packet num 2300
data_type 0 packet num 2400
data_type 0 packet num 2500
data_type 0 packet num 2600
data_type 0 packet num 2700
data_type 0 packet num 2800
data_type 0 packet num 2900
data_type 0 packet num 3000
data_type 0 packet num 3100
data_type 0 packet num 3200
data_type 0 packet num 3300
data_type 0 packet num 3400
data_type 0 packet num 3500
data_type 0 packet num 3600
data_type 0 packet num 3700
data_type 0 packet num 3800
data_type 0 packet num 3900
data_type 0 packet num 4000
data_type 0 packet num 4100
data_type 0 packet num 4200
data_type 0 packet num 4300
data_type 0 packet num 4400
data_type 0 packet num 4500
data_type 0 packet num 4600
data_type 0 packet num 4700
data_type 0 packet num 4800
data_type 0 packet num 4900
data_type 0 packet num 5000
data_type 0 packet num 5100
data_type 0 packet num 5200
data_type 0 packet num 5300
data_type 0 packet num 5400
data_type 0 packet num 5500
data_type 0 packet num 5600
data_type 0 packet num 5700
data_type 0 packet num 5800
data_type 0 packet num 5900
data_type 0 packet num 6000
data_type 0 packet num 6100
data_type 0 packet num 6200
data_type 0 packet num 6300
data_type 0 packet num 6400
data_type 0 packet num 6500
data_type 0 packet num 6600
data_type 0 packet num 6700
data_type 0 packet num 6800
data_type 0 packet num 6900
data_type 0 packet num 7000
data_type 0 packet num 7100
data_type 0 packet num 7200
data_type 0 packet num 7300
data_type 0 packet num 7400
data_type 0 packet num 7500
data_type 0 packet num 7600
data_type 0 packet num 7700
data_type 0 packet num 7800
data_type 0 packet num 7900
data_type 0 packet num 8000
data_type 0 packet num 8100
data_type 0 packet num 8200
data_type 0 packet num 8300
data_type 0 packet num 8400
data_type 0 packet num 8500
data_type 0 packet num 8600
data_type 0 packet num 8700
data_type 0 packet num 8800
data_type 0 packet num 8900
data_type 0 packet num 9000
data_type 0 packet num 9100
data_type 0 packet num 9200
data_type 0 packet num 9300
data_type 0 packet num 9400
data_type 0 packet num 9500
data_type 0 packet num 9600
data_type 0 packet num 9700
data_type 0 packet num 9800
data_type 0 packet num 9900
data_type 0 packet num 10000
data_type 0 packet num 10100
data_type 0 packet num 10200
data_type 0 packet num 10300
data_type 0 packet num 10400
data_type 0 packet num 10500
data_type 0 packet num 10600
data_type 0 packet num 10700
data_type 0 packet num 10800
data_type 0 packet num 10900
data_type 0 packet num 11000
data_type 0 packet num 11100
data_type 0 packet num 11200
data_type 0 packet num 11300
data_type 0 packet num 11400
data_type 0 packet num 11500
data_type 0 packet num 11600
data_type 0 packet num 11700
data_type 0 packet num 11800
data_type 0 packet num 11900
data_type 0 packet num 12000
data_type 0 packet num 12100
data_type 0 packet num 12200
data_type 0 packet num 12300
data_type 0 packet num 12400
data_type 0 packet num 12500
data_type 0 packet num 12600
data_type 0 packet num 12700
data_type 0 packet num 12800
data_type 0 packet num 12900
data_type 0 packet num 13000
data_type 0 packet num 13100
data_type 0 packet num 13200
data_type 0 packet num 13300
data_type 0 packet num 13400
data_type 0 packet num 13500
data_type 0 packet num 13600
data_type 0 packet num 13700
data_type 0 packet num 13800
data_type 0 packet num 13900
data_type 0 packet num 14000
data_type 0 packet num 14100
data_type 0 packet num 14200
data_type 0 packet num 14300
data_type 0 packet num 14400
data_type 0 packet num 14500
data_type 0 packet num 14600
data_type 0 packet num 14700
data_type 0 packet num 14800
data_type 0 packet num 14900
data_type 0 packet num 15000
data_type 0 packet num 15100
data_type 0 packet num 15200
data_type 0 packet num 15300
data_type 0 packet num 15400
data_type 0 packet num 15500
data_type 0 packet num 15600
data_type 0 packet num 15700
data_type 0 packet num 15800
data_type 0 packet num 15900
data_type 0 packet num 16000
data_type 0 packet num 16100
data_type 0 packet num 16200
data_type 0 packet num 16300
data_type 0 packet num 16400
data_type 0 packet num 16500
data_type 0 packet num 16600
data_type 0 packet num 16700
data_type 0 packet num 16800
data_type 0 packet num 16900
data_type 0 packet num 17000
data_type 0 packet num 17100
data_type 0 packet num 17200
data_type 0 packet num 17300
data_type 0 packet num 17400
data_type 0 packet num 17500
data_type 0 packet num 17600
data_type 0 packet num 17700
data_type 0 packet num 17800
data_type 0 packet num 17900
data_type 0 packet num 18000
data_type 0 packet num 18100
data_type 0 packet num 18200
data_type 0 packet num 18300
data_type 0 packet num 18400
data_type 0 packet num 18500
data_type 0 packet num 18600
data_type 0 packet num 18700
data_type 0 packet num 18800
data_type 0 packet num 18900
data_type 0 packet num 19000
data_type 0 packet num 19100
data_type 0 packet num 19200
data_type 0 packet num 19300
data_type 0 packet num 19400
data_type 0 packet num 19500
data_type 0 packet num 19600
data_type 0 packet num 19700
data_type 0 packet num 19800
data_type 0 packet num 19900
data_type 0 packet num 20000
data_type 0 packet num 20100
data_type 0 packet num 20200
data_type 0 packet num 20300
data_type 0 packet num 20400
data_type 0 packet num 20500
data_type 0 packet num 20600
data_type 0 packet num 20700
data_type 0 packet num 20800
data_type 0 packet num 20900
data_type 0 packet num 21000
data_type 0 packet num 21100
data_type 0 packet num 21200
data_type 0 packet num 21300
data_type 0 packet num 21400
data_type 0 packet num 21500
data_type 0 packet num 21600
data_type 0 packet num 21700
data_type 0 packet num 21800
data_type 0 packet num 21900
data_type 0 packet num 22000
data_type 0 packet num 22100
data_type 0 packet num 22200
data_type 0 packet num 22300
data_type 0 packet num 22400
data_type 0 packet num 22500
data_type 0 packet num 22600
data_type 0 packet num 22700
data_type 0 packet num 22800
data_type 0 packet num 22900
data_type 0 packet num 23000
data_type 0 packet num 23100
data_type 0 packet num 23200
data_type 0 packet num 23300
data_type 0 packet num 23400
data_type 0 packet num 23500
data_type 0 packet num 23600
data_type 0 packet num 23700
data_type 0 packet num 23800
data_type 0 packet num 23900
data_type 0 packet num 24000
data_type 0 packet num 24100
data_type 0 packet num 24200
data_type 0 packet num 24300
data_type 0 packet num 24400
data_type 0 packet num 24500
data_type 0 packet num 24600
data_type 0 packet num 24700
data_type 0 packet num 24800
data_type 0 packet num 24900
data_type 0 packet num 25000
data_type 0 packet num 25100
data_type 0 packet num 25200
data_type 0 packet num 25300
data_type 0 packet num 25400
data_type 0 packet num 25500
data_type 0 packet num 25600
data_type 0 packet num 25700
data_type 0 packet num 25800
data_type 0 packet num 25900
data_type 0 packet num 26000
data_type 0 packet num 26100
data_type 0 packet num 26200
data_type 0 packet num 26300
data_type 0 packet num 26400
data_type 0 packet num 26500
data_type 0 packet num 26600
data_type 0 packet num 26700
data_type 0 packet num 26800
data_type 0 packet num 26900
data_type 0 packet num 27000
data_type 0 packet num 27100
data_type 0 packet num 27200
data_type 0 packet num 27300
data_type 0 packet num 27400
data_type 0 packet num 27500
data_type 0 packet num 27600
data_type 0 packet num 27700
data_type 0 packet num 27800
data_type 0 packet num 27900
data_type 0 packet num 28000
data_type 0 packet num 28100
data_type 0 packet num 28200
data_type 0 packet num 28300
data_type 0 packet num 28400
data_type 0 packet num 28500
data_type 0 packet num 28600
data_type 0 packet num 28700
data_type 0 packet num 28800
data_type 0 packet num 28900
data_type 0 packet num 29000
data_type 0 packet num 29100
data_type 0 packet num 29200
data_type 0 packet num 29300
[2020-12-16 15:37:55.324] [console] [info]  Send Command: Set 0 Id 4 Seq 42  [command_channel.cpp] [Send] [243]`
请问这是什么原因，谢谢大家！

**Comment by Livox-SDK** [comment]
@Ganymedes-wang 
您好，这是正常的日志输出

**Comment by Ganymedes-wang** [comment]
@Livox-SDK 您好，那这个日志输出结果存放在什么位置，如何查看数据？
