### ISSUE TITLE
使用VS2019编译SDK（硬件上已经连接设备），但在VS2019上无法连接上设备。

### ISSUE THREAD

**Issue by Tony-TF** [Livox-SDK/Livox-SDK#119]
具体情况如下所示：
![a2e2d685ad6fe9bcbe73cdfbca74e7d](https://user-images.githubusercontent.com/35761167/114999690-aac19200-9ed4-11eb-89a9-2ea56ba526ab.png)
![d55189ed838209ea656bcd5254245d0](https://user-images.githubusercontent.com/35761167/114999699-ac8b5580-9ed4-11eb-9efc-1b82a5b5efe8.png)

**Comment by Livox-SDK** [comment]
@Tony-TF 
有两种可能的原因导致设备无法连接
1. LiDAR 无法同时连接 Viewer 和 SDK，在启动 SDK 时需要先将 Viewer 连接的 LiDAR 断开连接；
2. 请检查一下防火墙是否把 sdk 程序拦截，建议您在 windows defender 防火墙->允许的应用 中找到 lidar_lvx_sample 并删除，
然后重新运行 lidar_lvx_sample.exe 程序
