### ISSUE TITLE
I want to get one frame of data

### ISSUE THREAD

**Issue by yuyu19970716** [Livox-SDK/Livox-SDK#126]
Hello, I'm running./ lidar_lvx_sample-c "00000000000002&00000000000003&00000000000004" -L-t 10-p  I changed the time to 1s, I received 20 frames of data, I need to change the time to 0.1s, but I find that the time in the code needs to be of type int, I change it to type double, but I still receive 20 frames of data, I don't know what is the matter? Is it because I can't change anything in the code?

**Comment by gabrielheider** [comment]
Hi @yuyu19970716 ,
Did you solve this problem? 
Can you provide short example?
Thanks
