### ISSUE TITLE
Sync Livox mid 40 with Camera (GoPro)

### ISSUE THREAD

**Issue by ManChrys** [Livox-SDK/Livox-SDK#129]
Hello guys,

im very interested on livox mid 40 and i have the chance to try it before i buy it. I have a question as im quiet new. How can i sync livox with camera( GoPro), so i can give color to point cloud ?

Thanks in advance guys,

**Comment by Livox-SDK** [comment]
Hi ManChrys
this link may give you some help: https://github.com/Livox-SDK/livox_camera_lidar_calibration

**Comment by ManChrys** [comment]
@Livox-SDK thank you a lot!!! I will check it!!
