### ISSUE TITLE
is there any way to get subset of scan FOV

### ISSUE THREAD

**Issue by hahakid** [Livox-SDK/Livox-SDK#14]
![mid-40](https://user-images.githubusercontent.com/8140299/63565379-5816c200-c59b-11e9-9807-f0ee8d6f0103.gif)
it seems that the scanner firing the way as the above figure, my question is that, is there any way to get a subset of the total scan FOV.
![微信图片_20190823115532](https://user-images.githubusercontent.com/8140299/63565790-ff482900-c59c-11e9-892d-c2183514a3ca.png)

**Comment by Livox-SDK** [comment]
FOV is determined by optical design and cannot be modified by software.Or you can filter the parts you need based on the location of each point cloud.
