### ISSUE TITLE
./lidar_lvx_sample -c "3GGDJ5J0010017" -t 10执行不了

### ISSUE THREAD

**Issue by 2000long** [Livox-SDK/Livox-SDK#145]
![image](https://user-images.githubusercontent.com/90179254/132179448-206e9460-6dc4-43a4-9fd9-8d875cff1d4b.png)

**Comment by Livox-SDK** [comment]
您好 @2000long, 
-c 选项后面添加的是雷达的广播码，广播码包含了序列号和一个额外的数字 (1,2, or 3)，所以需要在 3GGDJ5J0010017 后面还需要加上 1
`./lidar_lvx_sample -c "3GGDJ5J00100171" -t 10`
