### ISSUE TITLE
How to read .lvx file

### ISSUE THREAD

**Issue by LitoNeo** [Livox-SDK/Livox-SDK#15]
Hello, I have some .lvx files created by Mid-40, and I want to get its data in my code, so I wonder if there is any tools or SDK or some other methods that can do this, thanks!

**Comment by Livox-SDK** [comment]
Hi:
You can download lvx file specifications from [here:]( https://www.livoxtech.com/mid-40-and-mid-100/downloads)

**Comment by liu978079474** [comment]
Hello, how to convert lvx file to pcd file format？

> Hi:
> You can download lvx file specifications from [here:](https://www.livoxtech.com/mid-40-and-mid-100/downloads)
