### ISSUE TITLE
receiving no ErrorMessage when running samples

### ISSUE THREAD

**Issue by benedikt-mayer-inmach** [Livox-SDK/Livox-SDK#151]
When I access the Livox device via the livox-viewer i get several errors from the device.
If i run the lidar samples (either lidar_sample or lidar_sample_cc) i don't receive any error codes.
In fact the callback never gets called. I changed l.299ff in lds_lidar.cpp accordingly:

`/** Callback function of Lidar error message. */`
`void LdsLidar::LidarErrorStatusCb(livox_status status, uint8_t handle, ErrorMessage *message) {`
`  printf("ERROR STATUS CB CALLED!");`
`...`

![livox_viewer_error](https://user-images.githubusercontent.com/62999772/136535444-e938238e-a848-446a-b3fe-667e1ac47e50.png)

System: Ubuntu 20.04
Livox: Horizon

**Comment by Livox-SDK** [comment]
Hi @bene-inmach 
As Livox Viewer shows，`0x40000040` is “Warning” but not “Error” state.
`LidarErrorStatusCb` will be called only when LiDAR is in "Error" state.
In lds_lidar.cpp, If LiDAR is in "Warning" state. `LdsLidar::OnDeviceChange(const DeviceInfo *info, DeviceEvent type)` will be called. And `p_lidar->info.status.status_code` will show the detail warning code.

**Comment by benedikt-mayer-inmach** [comment]
Thanks for the quick reply
