### ISSUE TITLE
Problem with ./lidar_sample

### ISSUE THREAD

**Issue by Shibaditya99** [Livox-SDK/Livox-SDK#167]
when I'm starting ./lidar_sample, I'ts giving me the values [I modified main.c program]. but after a certain value it's like exiting from the loop. so how can I put it in a infinite loop? or where?

for example:
here I'm printing the data like this
`
if(data->data_type == kExtendedCartesian){
    LivoxExtendedRawPoint *p_pointdata = (LivoxExtendedRawPoint *)data->data;
    printf("%d, %d, %d", p_point_data->x, p_point_data->y, p_point_data->z);
}
`

If you please check the main.c in the Livox-SDK/sample/lidar, I modified that "GetLidarData()" function. but unfortunately after a certain time it's like exiting from the loop! so how can I solve that?
And how to get the data as frame by frame?

**Comment by gabrielheider** [comment]
Hi @Shibaditya99 ,

How did you solve this problem? Can you provide short example?
