### ISSUE TITLE
lvx文件

### ISSUE THREAD

**Issue by ChenAGit** [Livox-SDK/Livox-SDK#176]
sdk中有没有将lvx文件转换为ply文件的方法，或者播放lvx文件获取点云数据的方法

**Comment by Livox-SDK** [comment]
您好, 
目前我们没有基于phy文件做相关的转换开源工具，
可以参考我们的数据格式做相关的二次开发：
**https://github.com/Livox-SDK/Livox-SDK/wiki/Livox-SDK-Communication-Protocol-Cn**

**Comment by ChenAGit** [comment]
有没有播放lvx文件的接口，就像livox viewer上播放那样？








在 2022-06-09 11:39:21，"livox" ***@***.***> 写道：

您好,
目前我们没有基于phy文件做相关的转换开源工具，
可以参考我们的数据格式做相关的二次开发：
https://github.com/Livox-SDK/Livox-SDK/wiki/Livox-SDK-Communication-Protocol-Cn
