### ISSUE TITLE
Livox SDK on Win10

### ISSUE THREAD

**Issue by mi4869** [Livox-SDK/Livox-SDK#19]
Hi,

I have followed instructions to compile the Livox SDK on Win10. After connecting my Mid-40 successfully, I run lidar_sample.exe following Step 4.2.2, and it shows the following figures. Is it normal? I dont know why the programme automatically stops.
 
![image](https://user-images.githubusercontent.com/46913176/69538737-eac16580-0fbd-11ea-9cbf-fe6d7b05a08d.png)

**Comment by ososinski** [comment]
The count seems to increase "0" corresponds to the lidar handle and "2670000" - "2900000" is the packet count, suggesting that the lidar works fine

The reason it stops is that the sample is designed to work for a number of seconds and stop.

If you go through the source code you will find the exact number.

**Comment by mi4869** [comment]
> The count seems to increase "0" corresponds to the lidar handle and "2670000" - "2900000" is the packet count, suggesting that the lidar works fine
> 
> The reason it stops is that the sample is designed to work for a number of seconds and stop.
> 
> If you go through the source code you will find the exact number.
> 
> If you want to visually confirm that the lidar works, use [Livox Viewer.exe ](https://www.livoxtech.com/mid-40-and-mid-100/downloads)

Thanks ososinski, it works using Livox Viewer. If I want to run [Livox ROS Driver](https://github.com/Livox-SDK/livox_ros_driver), do I need to run any files under Livox-SDK?

**Comment by ososinski** [comment]
Just follow the instructions for the ros-sdk installer, then

to run the visualisation:
`roslaunch livox_ros_driver livox_lidar_rviz.launch`

to run as standalone ros package ie for loam-livox
`roslaunch livox_ros_driver livox_lidar.launch`

Hope your project will be up and running soon ^_^

**Comment by mi4869** [comment]
I think the instruction is for Linux, but I am using Win10 as I need to use some softwares applicable for Win10 instead of Linux. It seems that I cannot build Livox ROS Driver correctly by following the instruction.

**Comment by ososinski** [comment]
Sorry I do not have any experience with ROS on windows, but the ROS wiki should have some hints on how to build packages

**Comment by Livox-SDK** [comment]
Livox ROS driver don't support windows
