### ISSUE TITLE
Livox Viewer 2 Crash before to launch

### ISSUE THREAD

**Issue by Reapper** [Livox-SDK/Livox-SDK#196]
Computer model : hp pavilion gaming 15-dk1003sf
OS : Linux 5.15.0-60-generic #66~20.04.1-Ubuntu
Desktop env: KDE Plasma

Issue:
When i run the software, a black screen appear on both screens ( laptop screen + aux screen) during few seconds and nothing happen.

How to proceed : 
Just run the `./LivoxViewer2.sh` in terminal

log attached from Livox Viewer 2
[log.txt](https://github.com/Livox-SDK/Livox-SDK/files/10842108/log.txt)

**Comment by raghavduddala** [comment]
Hey @Reapper , did you manage to get this working? I have the same issue ongoing.

**Comment by raghavduddala** [comment]
@Livox-Infra @Livox-SDK any help here please ? 
My OS: `Linux 5.15.0-72-generic #79~20.04.1-Ubuntu`

**Comment by Reapper** [comment]
Hi @raghavduddala, i install Windows on my PC ( dual boot ) and it's work, propably because they use Unreal engine to show and manage cloud points and the soft is more finish on windows. Try to launch the app on window via virtual machine or dual boot, i have not any success to run on linux 20.04

**Comment by Deeparaj-24** [comment]
I also faced the same issue, I solved it by upgrading the mesa library. The latest version of that library is not available on ubuntu(20.04) ppa.
Run the below command to check the version of the mesa library.
`glxinfo | grep "OpenGL version"`
Run the commands below to upgrade mesa library
`sudo add-apt-repository ppa:kisak/kisak-mesa`
`sudo apt update`
`sudo apt upgrade`

**Comment by MannyEzz** [comment]
@Deeparaj-24 I tried it and still have the same issue, did anyone figure out the solution for this issue?

**Comment by tradom73** [comment]
any progress? I too can not open viewer on ubuntu

**Comment by artem-kondratew** [comment]
the same problem. Have you solved it?

> any progress? I too can not open viewer on ubuntu
