### ISSUE TITLE
你好，请问下使用sample_cc的程序，如何实现程序启动和停止自由切换，谢谢！

### ISSUE THREAD

**Issue by 1111111111lyh** [Livox-SDK/Livox-SDK#20]
你好，我使用的是MID-100，使用示例代码sample_cc的源码，我想通过一个按钮来控制lidar的采样和停止采样，代码流程修改如下：1、点击“开始”按钮，调用   int ret = read_lidar.InitLdsLidar(cmdline_broadcast_code); 2、将LivoxEthPacket *data中的数据拷贝出；3、调用 read_lidar.DeInitLdsLidar();关闭本次采集数据；4、点击“关闭”按钮，结束本次采集；5、再次执行1操作，发现cloud_ch[0]->points.size() = 0，没有采集到数据。请问我的操作是有什么问题？我该如何实现我自由控制采集数据开关的功能，谢谢！

**Comment by Livox-SDK** [comment]
使用 LidarStartSampling接口使能点云数据采样；
使用 LidarStopSampling 接口停止点云数据采样，不要DeInitLdsLidar；
