### ISSUE TITLE
Compile error in release build type

### ISSUE THREAD

**Issue by KangJH** [Livox-SDK/Livox-SDK#23]
Hi Livox team,
I'm one of members in Seoul Robotics.
I'm facing a compile error while building Livox-SDK with my script.
Below is error message.
```
Livox-SDK/sdk_core/src/base/io_loop.cpp:85:19: error: unused variable ‘thread_id’ [-Werror=unused-variable]
   apr_os_thread_t thread_id = apr_os_thread_current();
```
I'm thinking the problem occures because I'm using "**cmake .. -DCMAKE_BUILD_TYPE=Release**" in my script. This makes the compiler ignore assert() syntax.
Could you simply add **(void)thread_id** in _IOLoop::RemoveDelegateSync_ to avoid compile error in case someone using Release build?

**Comment by Livox-SDK** [comment]
Thank you for your advice, we will fix this bug in next release.
