### ISSUE TITLE
适用于arm llinux的sdk

### ISSUE THREAD

**Issue by CnybTseng** [Livox-SDK/Livox-SDK#25]
请问有适用于arm linux的SDK吗？能否在嵌入式设备上使用？

**Comment by Livox-SDK** [comment]
您好！Livox SDK 可以在 Ubuntu 系统的 ARM (Nvidia TX2) 上正常使用

**Comment by CnybTseng** [comment]
那在不跑Ubuntu的ARM、比如海思Hi3559A上能使用吗？

**Comment by Livox-SDK** [comment]
您好！目前 Livox SDK 在非Ubuntu 系统的平台上没有验证过

**Comment by wbb-zygd** [comment]
Livox SDK 在Ubuntu 系统的平台上的任何ARM 处理器都可以使用吗？还是必须在Nvidia TX2上使用。

**Comment by Livox-SDK** [comment]
您好，@wbb-zygd ！理论上是可以的，但是我们没有在其他ARM处理器上做过充分测试
