### ISSUE TITLE
[request] Add export config.cmake file

### ISSUE THREAD

**Issue by UnaNancyOwen** [Livox-SDK/Livox-SDK#27]
Currently, Livox SDK doesn't export config.cmake files.
In general, libraries build with CMake provide config.cmake to find it.
It will be able to find the Livox SDK using <code>find_package(livox_sdk)</code> in CMakeLists.txt of user project.
It provides good experience for many developers.
Please consider to export config.cmake. Thanks,

**Comment by Livox-SDK** [comment]
Thank you for your advice, we will export config.cmake files in a future release.
