### ISSUE TITLE
Livox lidar ghost points in point cloud

### ISSUE THREAD

**Issue by nithi89** [Livox-SDK/Livox-SDK#32]
Hi I am trying to use the Livox mid-100 series lidar. The point cloud has ghost points as you can see in the point cloud attached.

pointcloud image: https://www.dropbox.com/s/4d9galew50uf3bd/35_ptcld_ghostpts.png?dl=0

corresponding camera image: https://www.dropbox.com/s/o4nq9jy9jbiap8v/35.bmp?dl=0

All objects in the scene are stationary (including cars). Can you please explain this behavior and also how to fix it?

Thank you.

**Comment by dleliuhin** [comment]
May be there are noise points due to high humidity. You can apply some noise removal filters for 3D point cloud data. See there: 
https://github.com/search?q=lidar+noise

**Comment by Livox-SDK** [comment]
Hi @nithi89. To analyze this behavior，can you provide us with pointcloud's lvx file (use Livox Viewer to record within 20s) and corresponding camera image.

**Comment by nithi89** [comment]
Hi, I realized the problem was a software error and not with the lidar, it
is fixed now. Thank you.

**Comment by meng-zha** [comment]
@nithi89 Hi, I met the similar problem with mid-100 lidar that there are noisy points along the border of obstacle. Do you remember what the software error you met was at that time?
