### ISSUE TITLE
sample/Lidar的例子中，雷达被遮挡的时候会调用OnLidarErrorStatusCallback么

### ISSUE THREAD

**Issue by qulee** [Livox-SDK/Livox-SDK#33]
printf("dirty_warn : %u\n", message->lidar_error_code.dirty_warn);

**Comment by Livox-SDK** [comment]
您好，雷达被遮挡的时候OnLidarErrorStatusCallback不会被调用。
在点云采样过程中，雷达被遮挡后有，SDK有两种方式会通知用户
（1）参照：[SDK通信协议](https://github.com/Livox-SDK/Livox-SDK/wiki/Livox-SDK-Communication-Protocol) 3.1 Package Format ，点云的数据包格式 status_code相应的字段dirty_warn 会被置位为1. 
（2）雷达被遮挡后，SDK会触发SetDeviceStateUpdateCallback()设置的回调函数。
例如sample/lidar的例子中，会触发void OnDeviceInfoChange(const DeviceInfo *info, DeviceEvent type)，其中 info->status 中也会记录相关的脏污预警信息。

**Comment by qulee** [comment]
Thanks&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"livox"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 上午10:49
收件人:&nbsp;"Livox-SDK/Livox-SDK"<Livox-SDK@noreply.github.com&gt;;
抄送:&nbsp;"Baslilon"<969248039@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Livox-SDK/Livox-SDK] sample/Lidar的例子中，雷达被遮挡的时候会调用OnLidarErrorStatusCallback么 (#33)





 
您好，雷达被遮挡的时候OnLidarErrorStatusCallback不会被调用。
 在点云采样过程中，雷达被遮挡后有，SDK有两种方式会通知用户
 （1）参照：SDK通信协议 3.1 Package Format ，点云的数据包格式 status_code相应的字段dirty_warn 会被置位为1.
 （2）雷达被遮挡后，SDK会触发SetDeviceStateUpdateCallback()设置的回调函数。
 例如sample/lidar的例子中，会触发void OnDeviceInfoChange(const DeviceInfo *info, DeviceEvent type)，其中 info-&gt;status 中也会记录相关的脏污预警信息。
