### ISSUE TITLE
livox horizon和imu时间同步

### ISSUE THREAD

**Issue by limeng1523** [Livox-SDK/Livox-SDK#34]
您好，我在用livox horizon和xsens的imu录数据，请问我怎么样才能得到同步的时间戳呢，我想知道硬件上需要怎么连接，我用的驱动是livox_ros_driver.谢谢!

**Comment by Livox-SDK** [comment]
您好，您可以参照 [LivoxIntegration](https://github.com/Livox-SDK/LivoxIntegration/blob/master/Integrating%20Livox%20LiDARs%20with%20INS.md) 中uINS的方式同步时间戳

**Comment by limeng1523** [comment]
您好，我现在想让livox的时间戳与ros系统的时间戳同步，请问要怎么做呢，谢谢
