### ISSUE TITLE
Warning when operating Livox Horizon

### ISSUE THREAD

**Issue by xmba15** [Livox-SDK/Livox-SDK#35]
Hi. I got the following warning when I connected Livox Horizon to see the point clouds on the Viewer:
0x40000040, which shows Dirty (as can be seen in the attached images). I already removed the protective film from the lidar.
![warning](https://user-images.githubusercontent.com/18694765/77394625-34428580-6de3-11ea-9a72-190b88f160f4.png)

![warning_window](https://user-images.githubusercontent.com/18694765/77394687-520fea80-6de3-11ea-8273-26f19701047a.png)

Can you help with this? Thank you very much.

**Comment by Livox-SDK** [comment]
Hi, @xmba15.
Could you confirm that the distance between the object and the Livox Horizon is less than 1m ? If so, Horizon may trigger dirty warning.
If you have questions about the quality of the lidar, It's recommended to issue at [ livox lidars google group](https://groups.google.com/forum/#!forum/livox-lidars)

**Comment by xmba15** [comment]
Hi, thank you for your reply.
The warning actually disappears as I point the lidar away from the nearby (less than 1m) obstacles.
I will post questions (if any) on google group next time.
Thanks for your support.
