### ISSUE TITLE
"hour" missing in timestamp type 3 on MID 40

### ISSUE THREAD

**Issue by Jonas233** [Livox-SDK/Livox-SDK#36]
Hey LIVOX,
We are currently using the MID-40 and needed a UTC timestamp. After resolving the issue (Issue #31) regarding UTC on the mid40 including firmware upgrade we ran into further problems.

The main issue was that we couldn’t get anything else than 0 reading the byte 3 “hour” in the timestamp. Everything else looked fine including the microseconds. After looking through some of the source code we noticed that the {utc_time_req->hour} in {ParseRmcTime} was never set to anything (found in the command_impl.cpp).
We fixed the issue by adding the code underneath between line 213 and 214 in command_impl.cpp. 

`utc_time_reg->hour = hour;`

**Comment by Livox-SDK** [comment]
Hi @Jonas233 ，
Thank you for pointing this out and we will fix this problem as soon as possible
