### ISSUE TITLE
I can't remove from SDK a device connected before on runtime

### ISSUE THREAD

**Issue by fjserrano** [Livox-SDK/Livox-SDK#41]
Hi all.

  I have a library for my own projects to works with livox lidars based on your Livox-SDK. Now I am using Livox Horizon.

  I am develop for connect and disconnect Lidars on runtime, and In my network I have 2 o 3 PCs that can connect to Lidars devices. Actually only one Lidar send data to one PC. This is OK, but I want in runtime (Without reset my software or Livox-SDK) connect and disconnect to any lidar. 

  The problem is the next:

  - In my software when I send code broadcast to connect to one device calls to Livox-SDK function of "AddLidarToConnect(...)". And the software make all the operations and it have the Lidar sampling perfectly.
  - When I send a command to my software I want to stop sampling device "LidarStopSampling(...)", disconnect device "DisconnectDevice(...)" and with this, I want to free the Lidar to connect from other PC, but the the SDK automatically connects to the device and the SDK doesn't free the Lidar to connect from other PC.

  I thinks it is because I have the function "AddLidarToConnect(...)" to add the Lidar in a list on SDK but I don't call other function to remove from this list on SDK. I read the documentation and I don't see it in the documentation this type of function, Can you tell me what function I need to use to free the Lidar to connect to other PC without closing the SDK on runtime??.

  If you don't understand or you need more information tell to me.

Best Regards.

**Comment by Livox-SDK** [comment]
Hi @fjserrano ,

You are right! But there is no good way to solve this problem at present. We will plan to add API to remove lidar from list on SDK corresponding to "AddLidarToConnect(...)"
