### ISSUE TITLE
树莓派平台编译错误

### ISSUE THREAD

**Issue by liang-tang** [Livox-SDK/Livox-SDK#45]
/home/ubuntu/Livox-SDK/third_party/apr/include/apr-1/apr.h:359:10: error: unknown type name ‘off64_t’
  359 | typedef  off64_t           apr_off_t;
      |          ^~~~~~~

**Comment by Livox-SDK** [comment]
您好 @liang-tang ，
可以先使用 `sudo apt-get install libapr1-dev` 替代 `sudo ./third_party/apr/apr_build.sh` 步骤.
后续我们会想办法解决该问题.

**Comment by liang-tang** [comment]
@Livox-SDK 感谢回复。
安装上述方式进行编译，发现还是出现同样的问题。
系统使用的官方推荐的系统
![image](https://user-images.githubusercontent.com/16251761/80374573-6c008980-88c9-11ea-9c8d-1a30ce1db80f.png)

**Comment by liang-tang** [comment]
@Livox-SDK 编译通了，非常感谢。

**Comment by doubelejjyy** [comment]
你好，你是怎么解决的，跟你遇到一样的情况

**Comment by liang-tang** [comment]
@doubelejjyy 试一试https://github.com/liang-tang/Livox-SDK
