### ISSUE TITLE
raspberry

### ISSUE THREAD

**Issue by Jweiiii** [Livox-SDK/Livox-SDK#46]
您好，在树莓派下cmake，有错误，请问需要改哪里

pi@raspberrypi:~/Livox-SDK $ cd build && cmake ..
CMake Error at /usr/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:174 (file):
  file failed to open for writing (No such file or directory):

    /home/pi/Livox-SDK/build/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

CMake Error: Could not open file for write in copy operation /home/pi/Livox-SDK/build/CMakeFiles/3.13.4/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:186 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

**Comment by liang-tang** [comment]
没安装cmake吗?

**Comment by Jweiiii** [comment]
安装了
pi@raspberrypi:~ $ cmake -version
cmake version 3.13.4
CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by liang-tang** [comment]
哪个版本的树莓派？

**Comment by Jweiiii** [comment]
Raspberry Pi 2 Model B Rev 1.1

**Comment by liang-tang** [comment]
https://github.com/liang-tang/Livox-SDK/commit/522aab4db249b9b12418687758a06f4ae2957c6d

**Comment by liang-tang** [comment]
建议换成树莓派3b或者4b，安装64位操作系统，执行下面的脚本安装环境
https://github.com/liang-tang/Livox-SDK/blob/master/script/install_pi.sh

**Comment by liang-tang** [comment]
https://docs.google.com/document/d/14nue8maXYg1HSuOTEA1Ccmx5Bd9_OfFGLZPchpHolGg/edit?usp=sharing

**Comment by Jweiiii** [comment]
好的，谢谢啦
