### ISSUE TITLE
关于Livox设备点云数据的坐标零点 ？

### ISSUE THREAD

**Issue by shenshen927** [Livox-SDK/Livox-SDK#48]
请问收到的Livox设备点云数据的坐标零点在什么位置？这个零点可以通过配置设置么？
另外，如何将收到的点云转化为用户的自定义坐标系中坐标点？谢谢

**Comment by Livox-SDK** [comment]
关于坐标系，产品（mid-40/mid-70/horizion/tele-15）手册中有详细说明，horizon 的点云坐标零点位于 LiDAR 机身的窗口玻璃上。
产品手册下载地址：
[下载中心](https://www.livoxtech.com/cn/downloads)

**Comment by shenshen927** [comment]
收到，多谢~
