### ISSUE TITLE
关于雨雪雾的抗干扰能力

### ISSUE THREAD

**Issue by shenshen927** [Livox-SDK/Livox-SDK#50]
在Mid40的手册中看到有抗雨雾的功能，而Horizon中没有看到。请问下，Mid系列和Horizon哪个抗雨雪雾的抗干扰能力更好一些？

**Comment by Livox-SDK** [comment]
Livox 的MID系列和Horizon，包括Tele系列均有抗雨雪雾尘的功能。但是针对雨雪雾尘噪点的处理方案不同。
1.  MID系列将这类噪点直接过滤，即将这类噪点的深度置为0；
2.  Horizon 、Tele 则是在点云信息中加入了8 bits 的 tag 信息，tag信息里面包含点云为噪点的置信度，噪点可能为雨，雾，灰尘等，上层算法可以根据这个置信度采取合适的滤波方式进行噪点过滤。
有关 tag 信息更详细的内容，请参考[用户手册](https://www.livoxtech.com/3296f540ecf5458a8829e01cf429798e/assets/horizon/Livox%20Horizon%20%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C%20v1.0.pdf) P16-P17 的点云数据说明。

**Comment by shenshen927** [comment]
噪点深度置为0，意思是将z值置为0么？

**Comment by Livox-SDK** [comment]
噪点深度为0， 即 x、y、z 值都置为0
