### ISSUE TITLE
SDK 中关于whitelist的含义

### ISSUE THREAD

**Issue by xielinjiang** [Livox-SDK/Livox-SDK#54]
在阅读SDK代码时，频繁遇到很多变量或者注释里面含有 whitelist，请问 whitelist有什么特殊含义吗？

**Comment by Livox-SDK** [comment]
您好，@xielinjiang
whiltelist 表示 LiDAR 设备白名单，在 whitelist 中的设备，SDK 将会与 LiDAR 建立连接 。

**Comment by xielinjiang** [comment]
理解了，非常感谢！
