### ISSUE TITLE
设备接入后频繁打印出StateChange告警信息，何故？

### ISSUE THREAD

**Issue by shenshen927** [Livox-SDK/Livox-SDK#55]
在SDK-demo的基础上开发了个小功能，能够接受点云数据，但控制台上会频繁打印StateChange的告警信息，不知道为什么会出现这个告警？我需不需要处理，该如何处理？
连接的设备是Horizon，打印信息是：
[WARNING] Lidar sn: ... StateChange!!!
OnDeviceChange broadcast code ... update type 2

**Comment by Livox-SDK** [comment]
您好，以上日志表明雷达推送了：
(1) 设备切换工作模式的进度; 
或者是
(2)设备内部状态预警信息；
具体还需要结合其他日志信息判断。
SDK-demo中是否有：Device State Change Progress 或者 Device State Error Code 类似这些日志的相关信息。
