### ISSUE TITLE
如何打开Mid100的雨雾模式

### ISSUE THREAD

**Issue by pxlong** [Livox-SDK/Livox-SDK#56]
您好，请问如何打开Mid100的雨雾模式？我是通过Livox ROS driver来得到点云数据。
谢谢

**Comment by Livox-SDK** [comment]
您好，Livox ROS driver 目前不支持 Mid 100 的雨雾模式开关。
但是 Livox-SDK 有支持 Mid 100 雨雾模式开关的接口，建议您：
（1）可以直接使用 Livox-SDK；
（2）Livox ROS driver 是在 Livox-SDK 的基础上实现的，可以在目前 Livox ROS driver 的基础上进行二次开发 实现该功能。

**Comment by pxlong** [comment]
我的建议是：你们能不能把这个功能做得更加方便用户来操作？
比方说，用一行命令就turn on雨雾模式，或者可以在Livox Viewer里面进行设置并报存。

我看到Livox Viewer里面现在能打开雨雾模式，但是不能保存一直生效。我把viewer关掉，再重新打开，雨雾模式又是off的状态了。

**Comment by pxlong** [comment]
@Livox-SDK 能支持一下吗？我购买了你们的lidar
