### ISSUE TITLE
How do I get the target reflectivity on the Mid-40?

### ISSUE THREAD

**Issue by crea397** [Livox-SDK/Livox-SDK#58]
Hi,

The reflectivity of 0~150 based on the Lambertian reflection model can be obtained.

However, I don't see any values from 151~255 based on the reflectivity of target objects.

Why is this? How do I do this?

Thanks!

**Comment by Livox-SDK** [comment]
Hi, @crea397  
target objects with reflectivity values over 150 are usually things with different reflection model like retro-reflector. For most objects, the reflectivity value will be between 0~150.

**Comment by crea397** [comment]
Thank you for your reply!
I was able to understand the cause of the problem.
