### ISSUE TITLE
Build failed: could not find PkgConfig

### ISSUE THREAD

**Issue by gworkman** [Livox-SDK/Livox-SDK#6]
I am trying to build the SDK from the latest release. When I run `cmake ..` the output is the following:

-- main project dir: /home/ubuntu/Livox-SDK
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/Livox-SDK/build

If I try to continue and run `make`, the build fails with 
```
fatal error: apr_general.h: No such file or directory
  #include "apr_general.h"
```
However, I checked and the correct libraries are installed and the `apr_general.h` file exists in `/usr/include/apr-1.0/`

**Comment by Livox-SDK** [comment]
It seems that there is no pkgconfig in your system, so cmake can't find the apr-lib and will fail in make process, please check your cmake has been properly installed.
