### ISSUE TITLE
Question about the lvx format

### ISSUE THREAD

**Issue by kentaroy47** [Livox-SDK/Livox-SDK#63]
I'm having trouble reading out .lvx files on python.
My script was working for MID, but it's not working on Horizon dispute the data type change.
I noticed some changes on the Specifications on lvx format.

![Screenshot from 2020-06-11 18-40-18](https://user-images.githubusercontent.com/39611941/84370398-272f7880-ac13-11ea-9c31-0abcfff699e1.png)
While the frame header is 32bytes, only the first 24 bytes are specified in the Specifications. (I thought it used to be the length of the current frame?)
What is the last 8 bytes?

Thanks!
https://www.livoxtech.com/3296f540ecf5458a8829e01cf429798e/downloads/Livox%20Viewer/LVX%20Specifications%20EN_20190924.pdf

**Comment by kentaroy47** [comment]
Seems like this is a bug, only 24bytes in the frame header..

**Comment by Livox-SDK** [comment]
Hi, @kentaroy47 
Yes, It's a bug on LVX Specifications v1.0. frame header actually only have 24bytes.
Horizon use new version of lvx format V1.1. you can refer to new version of [LVX Specification V1.0](https://terra-1-g.djicdn.com/65c028cd298f4669a7f0e40e50ba1131/Download/LVX%20Specifications.pdf)

**Comment by kentaroy47** [comment]
Thanks!
You should link this document to the Horizon download page.. It will cause
much less confusions

2020年6月12日(金) 21:39 livox <notifications@github.com>:
