### ISSUE TITLE
horzion 数据1s2000个

### ISSUE THREAD

**Issue by Wingflysky** [Livox-SDK/Livox-SDK#65]
用sdk，无论是打印还是不打印，1s都在2000个左右，无法实现每秒24000个点

**Comment by EulerWong** [comment]
你这个问题描述得不清楚啊

**Comment by Lavinci** [comment]
你好，我跟一楼是一起的，我来具体描述下，我们运行sdk中sample_cc中的lidar示例程序，在回调函数GetLidarDataCb中，我们对kExtendCartesian这个类型下加了cnt进行计数，发现一秒只有2000个data的xyz点，低于预期
我们想一秒拿到尽可能多的数据，应该怎么操作？

**Comment by Livox-SDK** [comment]
您好，
每次回调中并不是只有一个点，而是包含 data_num 个点
`void LdsLidar::GetLidarDataCb(uint8_t handle, LivoxEthPacket *data,
                              uint32_t data_num, void *client_data)`
可以通过 例如 `p_point_data[data_num-1]` 获取该数据包的其它点云数据
`LivoxExtendRawPoint *p_point_data = (LivoxExtendRawPoint *)data->data`

**Comment by Lavinci** [comment]
好的，已经解决，谢谢啦~
你可以关闭这个问题了😁
