### ISSUE TITLE
W10VS2015编译livox_sdk_static报错

### ISSUE THREAD

**Issue by XGP810364691** [Livox-SDK/Livox-SDK#68]
D:\VS\VC\include\type_traits(1494): error C2893: 未能使函数模板“unknown-type std::invoke(_Callable &&,_Types &&...)”专用化
1>  D:\VS\VC\include\type_traits(1494): note: 用下列模板参数:
1>  D:\VS\VC\include\type_traits(1494): note: “_Callable=_Decayed &”
1>  D:\VS\VC\include\type_traits(1494): note: “_Types={BroadcastDeviceInfo *}”
1>  D:\VS\VC\include\functional(210): note: 参见对正在编译的函数 模板 实例化“void std::_Invoke_ret<_Rx,_Callable&,_Ty>(std::_Forced<_Rx,true>,_Callable &,_Ty &&)”的引用
1>          with
1>          [
1>              _Rx=void,
1>              _Callable=_Decayed,
1>              _Ty=BroadcastDeviceInfo *
1>          ]
1>  D:\VS\VC\include\functional(208): note: 编译类 模板 成员函数“void std::_Func_impl<_Decayed,_Alloc,_Ret,BroadcastDeviceInfo *>::_Do_call(BroadcastDeviceInfo *&&)”时
1>          with
1>          [
1>              _Alloc=std::allocator<int>,
1>              _Ret=void
1>          ]
1>  D:\VS\VC\include\functional(136): note: 参见对正在编译的类 模板 实例化“std::_Func_impl<_Decayed,_Alloc,_Ret,BroadcastDeviceInfo *>”的引用
1>          with
1>          [
1>              _Alloc=std::allocator<int>,
1>              _Ret=void
1>          ]
1>  D:\VS\VC\include\functional(339): note: 参见对正在编译的类 模板 实例化“std::_Is_large<_Myimpl>”的引用
1>  D:\VS\VC\include\functional(318): note: 参见对正在编译的函数 模板 实例化“void std::_Func_class<_Ret,BroadcastDeviceInfo *>::_Reset_alloc<_Ty,std::allocator<_Ty>>(_Fx &&,const _Alloc &)”的引用
1>          with
1>          [
1>              _Ret=void,
1>              _Ty=int,
1>              _Fx=int,
1>              _Alloc=std::allocator<int>
1>          ]
1>  D:\VS\VC\include\functional(318): note: 参见对正在编译的函数 模板 实例化“void std::_Func_class<_Ret,BroadcastDeviceInfo *>::_Reset_alloc<_Ty,std::allocator<_Ty>>(_Fx &&,const _Alloc &)”的引用
1>          with
1>          [
1>              _Ret=void,
1>              _Ty=int,
1>              _Fx=int,
1>              _Alloc=std::allocator<int>
1>          ]
1>  D:\VS\VC\include\functional(484): note: 参见对正在编译的函数 模板 实例化“void std::_Func_class<_Ret,BroadcastDeviceInfo *>::_Reset<int>(_Fx &&)”的引用
1>          with
1>          [
1>              _Ret=void,
1>              _Fx=int
1>          ]
1>  D:\VS\VC\include\functional(484): note: 参见对正在编译的函数 模板 实例化“void std::_Func_class<_Ret,BroadcastDeviceInfo *>::_Reset<int>(_Fx &&)”的引用
1>          with
1>          [
1>              _Ret=void,
1>              _Fx=int
1>          ]
1>  e:\prj\livox-sdk\sdk_core\src\device_manager.h(56): note: 参见对正在编译的函数 模板 实例化“std::function<void (BroadcastDeviceInfo *)>::function<int>(_Fx)”的引用
1>          with
1>          [
1>              _Fx=int
1>          ]
1>  e:\prj\livox-sdk\sdk_core\src\device_manager.h(56): note: 参见对正在编译的函数 模板 实例化“std::function<void (BroadcastDeviceInfo *)>::function<int>(_Fx)”的引用
1>          with
1>          [
1>              _Fx=int
1>          ]
1>  device_discovery.cpp

**Comment by Livox-SDK** [comment]
您好，@XGP810364691 ,
由于 Livox-SDK 目前使用了 C++11 的一些特性，需要 Visual Studio 2015 Update3 及以上版本才能正常编译。
