### ISSUE TITLE
Adjusting the spin rate of the Livox Mid 40

### ISSUE THREAD

**Issue by bultmann-s** [Livox-SDK/Livox-SDK#7]
Hi, I am interested in achieving a higher total coverage of the scan area in a given time while trading off against a lower resolution along the scan lines of the pattern.

Is it possible to adjust the spinning rate of the turning mirrors / prisms of the Livox Mid 40 as a parameter using the Livox-SDK ?

**Comment by Livox-SDK** [comment]
Hi bultmann-s:
The current scanning speed is the optimal solution regarding to power consumption, service lifetime point cloud density and eyes-safety.  Especially for eyes-safety ,The scanning pattern of Livox MID-40 is much more complicated than other LiDARs , so we need to be very careful to decide whether to open this interface to users. Thank you for your feed back.
