### ISSUE TITLE
MID40 tag

### ISSUE THREAD

**Issue by Wingflysky** [Livox-SDK/Livox-SDK#70]
我从上位机拿到mid40数据，tag值都为0，请问这是固件问题还是什么原因？

**Comment by Wingflysky** [comment]
好像，目前sdk，没有tag

**Comment by SkylerZheng45** [comment]
我也有这个问题，tele-15也没有tag

**Comment by Wingflysky** [comment]
> 我也有这个问题，tele-15也没有tag
horzion是有tag的，tele我目前手上没有测试

**Comment by Wingflysky** [comment]
https://github.com/Livox-SDK/Livox-SDK/wiki/Livox-SDK-Communication-Protocol#1-summary，tele15应该是有的，mid40目前没有
