### ISSUE TITLE
How to read lvx files with python

### ISSUE THREAD

**Issue by SkylerZheng45** [Livox-SDK/Livox-SDK#71]
I have an lvx file generated by tele-15. Is there any way I can access the data with python so I can use it in my code?

**Comment by mar2194** [comment]
Hi Skyler,

I am currently mentoring a high school student who wrote an excellent file reader for .lvx files in Python. I will have her merge a pull request to the openpylivox repository (which has been forked to GitHub.com/Livox-SDK) as soon as possible.

**Comment by kentaroy47** [comment]
I made a script to read lvx files with python. 
Hope it helps.

https://gist.github.com/kentaroy47/6e8081df81785342cbf8daedde1928ce

**Comment by SkylerZheng45** [comment]
@mar2194 sounds great thanks!
