### ISSUE TITLE
UDP Broadcast not working in secured network. Is UDP Unicast possible?

### ISSUE THREAD

**Issue by codegrafix** [Livox-SDK/Livox-SDK#73]
Due to some network regulations broadcast is not allowed in our network.
Is it possible to enable UDP unicast?

For example with Velodyne sensors its possible to specify the destination port and ip address so that not all other devices get flooded.
Can you please make this also available?

We plan to run multiple sensors in our network and we would highly welcome a fast reply on this.

**Comment by Livox-SDK** [comment]
Hi, @codegrafix 

Currently, It's not possible to use UDP unicast only.
Handshake mechanism between LiDAR and Livox-SDK relys on UDP broadcast.
But after connection establishment，LiDAR will communicate with Livox-SDK with UDP unicast.

**Comment by codegrafix** [comment]
Hi @Livox-SDK,
thanks for the information. Do you have any plans to support a direct connection without UDP for the future?

**Comment by Livox-SDK** [comment]
Hi @codegrafix 
We still have no plans to do it at present.

**Comment by codegrafix** [comment]
O.K. I'm looking forward to this!

**Comment by codegrafix** [comment]
Is it possible to skip the broadcast/handshake in order to create a direct connection? **Currently this is a show stopper!** Would be very happy If you can provide at least some recommendations.
