### ISSUE TITLE
What is the CRC checksum algorithm to compute CRC-16 and CRC-32 in communication protocol?

### ISSUE THREAD

**Issue by roya-correct-ai** [Livox-SDK/Livox-SDK#81]
Hi there
I want to write command and get the IMU push frequency from the lidar, the problem is that I do not know how to compute the CRC-16 for Frame Header Checksum and CRC-32 for Whole Frame Checksum to make a command frame.
I would appreciate it if you guide me on this issue.
Thanks in advance
Roya

**Comment by Livox-SDK** [comment]
Hi @roya-correct-ai，
There is a C++ source code of  [Compute Frame Checksum](https://github.com/Livox-SDK/Livox-SDK/blob/master/sdk_core/src/comm/sdk_protocol.cpp)
