### ISSUE TITLE
On the use of time synchronization about mid-40

### ISSUE THREAD

**Issue by nishiljmao** [Livox-SDK/Livox-SDK#91]
I have successfully run SDK in the lidar_ utc_ sync, and successfully connected to GPS. 

![微信图片_20201009094319](https://user-images.githubusercontent.com/68581732/95539726-b746c880-0a21-11eb-9b0c-b6653c23efb6.png)
But the time stamp in LVX file is still zero per second, not displaying GPS time. How to solve this problem?

**Comment by Livox-SDK** [comment]
Hi @nishiljmao 
This is because lidar_sample_cc has connected lidar. 
So lidar_utc_sync can't connect lidar at the same time and sychronize utc time to lidar.
You need to combine lidar_ut_sync and lidar_sample_cc's source code.
