### ISSUE TITLE
Time Synchronization of Mid-100/Mid-40 using PTP

### ISSUE THREAD

**Issue by AvGladiss** [Livox-SDK/Livox-SDK#93]
I am trying to time-sync my Mid-100 (Firmware version 3.8) to a PTP master clock (hardware clock available and used). I have set up the PTP master clock following your instructions in https://github.com/Livox-SDK/Livox-SDK/wiki/Timestamp-Synchronization#Appendix. Using Wireshark, we see `Sync Messages` and `Follow Up` messages from the PTP master clock, and `Delay_Req messages` from the Mid40s. However, Livox Viewer 0.8.0 states that there is no 1588 Signal.

**Comment by AvGladiss** [comment]
I am sorry, I forgot to open UDP port 319 for receiving the `Delay_Req` messages and therefore, the grand master did not send the `Delay_Resp` messages....

**Comment by IKAROS93** [comment]
HI，my friend ,could you please tell me how to open the UDP port 319(139)? THANKS!@AvGladiss
