### ISSUE TITLE
LOG_ERROR("DeviceDiscovery Create Socket Failed")

### ISSUE THREAD

**Issue by cuiDarchan** [Livox-SDK/Livox-SDK#95]
in device_discovery.cpp  file
in  bool DeviceDiscovery::Start  function
SDK2.0 version . 
In most cases, the device link is normal. 
Occasionally LOG_ERROR("DeviceDiscovery Create Socket Failed") .
There are 7 mid40 connected to the network .
Thank you very much !

**Comment by cuiDarchan** [comment]
Env: Ubuntu 16.04

**Comment by Livox-SDK** [comment]
Hi @cuiDarchan 
This is because SDK2.0 doesn‘t create socket with reuse_port option.
This bug has been fix. It's recommended to update your SDK version to 2.2.0.

**Comment by cuiDarchan** [comment]
> Hi @cuiDarchan
> This is because SDK2.0 doesn‘t create socket with reuse_port option.
> This bug has been fix. It's recommended to update your SDK version to 2.2.0.
Thank you very much！
