### ISSUE TITLE
Lidar CMD 0x06 support for Avia triple return mode

### ISSUE THREAD

**Issue by ryan-brazeal-ufl** [Livox-SDK/Livox-SDK#97]
Hello,
Can you please update the SDK to include how to command an Avia sensor to utilize triple return mode. Within the [current SDK document for lidar command 0x06: set lidar return mode](https://github.com/Livox-SDK/Livox-SDK/wiki/Livox-SDK-Communication-Protocol#0x06-set-lidar-return-mode) only single and dual return modes are listed.
Thanks,
Ryan

**Comment by Livox-SDK** [comment]
Hi @ryan-brazeal-ufl 
Thank you for pointing this out. 
SDK docunment has been updated. [triple mode correseponding to 0x03.](https://github.com/Livox-SDK/Livox-SDK/wiki/Livox-SDK-Communication-Protocol#0x06-set-lidar-return-mode)

**Comment by ryan-brazeal-ufl** [comment]
I believe you also need to update **0x07 Get LiDAR Return Mode** documentation with the 0x03 return value.

**Comment by rlabs-oss** [comment]
Are there any plans to update the Mid-40 firmware to support multiple returns in one firmware version?

**Comment by Livox-SDK** [comment]
> I believe you also need to update **0x07 Get LiDAR Return Mode** documentation with the 0x03 return value.
**0x07 Get LiDAR Return Mode** also has been updated.

**Comment by Livox-SDK** [comment]
> Are there any plans to update the Mid-40 firmware to support single and multiple returns in one firmware version?
Hi @rlabs-oss 
We are sorry that we have no plans to update the Mid40 firmware version so far.
